spin_manifest_version = "1"
authors = ["macolso <mackenzie.olson@fermyon.com>"]
description = ""
name = "stargazer_counter"
trigger = { type = "http", base = "/" }
version = "0.1.1"

[variables]
gh_auth_token = { required = true }
owner = { required = true }
repo = { required = true }

[[component]]
id = "star-counter"
source = "app.wasm"
allowed_http_hosts = ["https://api.github.com"]
key_value_stores = ["default"]

[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]

[component.config]
gh_auth_token = "{{ gh_auth_token }}"
owner = "fermyon"
repo = "spin"

[[component]]
source = { url = "https://github.com/radu-matei/spin-kv-explorer/releases/download/v0.7.0/spin-kv-explorer.wasm", digest = "sha256:31a7ad7d7f72cdfa77855e4fe1a607bcdd0129d1ca4bbeff599e6ec09c8ce93c" }
id = "kv-explorer"
# add or remove stores you want to explore here
key_value_stores = ["default"]
[component.trigger]
route = "/internal/kv-explorer/..."

[[component]]
id = "api"
source = "api/target/api.wasm"
key_value_stores = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "npm run build"
workdir = "api"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "chart"
files = [ { source = "chart/static", destination = "/" } ]
[component.trigger]
route = "/static/..."
