spin_manifest_version = "1"
authors = ["macolso <mackenzie.olson@fermyon.com>"]
description = ""
name = "stargazer_counter_v2"
trigger = { type = "http", base = "/" }
version = "0.1.2"

[variables]
gh_auth_token = { required = true }
owner = { required = true }
repo = { required = true }

[[component]]
id = "star-counter"
source = "app.wasm"
allowed_http_hosts = ["https://api.github.com"]
sqlite_databases = ["default"]
key_value_stores = ["default"]

[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]

[component.config]
gh_auth_token = "{{ gh_auth_token }}"
owner = "fermyon"
repo = "spin"